#!/bin/bash

main () {

    action="${1}"
    cmd="${@:2}"

    if [ ${action} = "copy" ]; then
        fCopy ${cmd}
    elif [ ${action} = "view" ]; then
        fView ${cmd}
    elif [ ${action} = "exec" ]; then
        fExec ${cmd}
    elif [ ${action} = "all" ]; then
        fView ${cmd} && fCopy ${cmd} && fExec ${cmd}
    fi

}

fCopy () {
    echo -n ${@} | xclip -sel clip
}

fView () {
    echo ${@}
}

fExec () {
    ${@}
}

main ${@}