#!/usr/bin/env bash

# Mode DEBUG
#set -x

# VARS
DIR_CONF=$HOME/.config/txtweet
FILE_CONF=$DIR_CONF/config
FILE_TWEET=$HOME/twtweet.txt
CURRENT_DATETIME=`date +%FT%T`
ARG_VIEW=0
ARG_EDIT=0
ARG_CATEGORY=0
ARG_URL=0
ARG_TWEET=0

# FUNCTIONS
header(){
    cat << EOF >> $FILE_TWEET
# Twtweet est un programme simple permettant de garder des URLs dans un simple fichier .txt

DATE                    CATEGORY        URL : DESCRIPTION
==========================================================================
EOF
}

view(){
    less $FILE_TWEET
}

tweet(){
    if [ ${#CATEGORY} -gt 8 ]; then
        echo -e "$CURRENT_DATETIME\t$CATEGORY\t$URL : $TWEET" >> $FILE_TWEET
    else 
        echo -e "$CURRENT_DATETIME\t$CATEGORY\t\t$URL : $TWEET" >> $FILE_TWEET
    fi
}

init(){
    if [ ! -e $DIR_CONF ]; then
        mkdir -p $DIR_CONF
        echo -e "FILE_TWEET=$FILE_TWEET" > $FILE_CONF
    fi

    source $FILE_CONF

    if [ ! -f $FILE_TWEET ]; then
        header
    fi
}

edit_conf(){
    if type nvim > /dev/null 2>&1; then nvim $FILE_CONF;
    elif type vim > /dev/null 2>&1; then vim $FILE_CONF;
    elif type vi > /dev/null 2>&1; then vi $FILE_CONF; fi
}

check_args(){
    if [ $ARG_EDIT -eq 0 ] && [ $ARG_CATEGORY -eq 0 ] && [ $ARG_URL -eq 0 ] && [ $ARG_TWEET -eq 0 ] && [ $ARG_VIEW -eq 0 ]; then
        usage
    fi
    # If EDIT
    if [ $ARG_EDIT -eq 1 ] && ([ $ARG_CATEGORY -eq 1 ] || [ $ARG_URL -eq 1 ] || [ $ARG_TWEET -eq 1 ] || [ $ARG_VIEW -eq 1 ]); then
        usage
    fi
    # If VIEW
    if ([ $ARG_EDIT -eq 1 ] || [ $ARG_CATEGORY -eq 1 ] || [ $ARG_URL -eq 1 ] || [ $ARG_TWEET -eq 1 ]) && [ $ARG_VIEW -eq 1 ]; then
        usage
    fi
    # If TWEET
    if [ $ARG_EDIT -eq 1 ] || ([ $ARG_CATEGORY -eq 1 ] && [ $ARG_URL -eq 1 ]) && [ $ARG_VIEW -eq 1 ]; then
        usage
    fi
}

# ARGS
usage(){
    echo -e "View : "
    echo -e "$0 -l"
    echo -e "Edit configuration : "
    echo -e "$0 -e"
    echo -e "Tweet :"
    echo -e "$0 -c <CATEGORY> -u <URL> -m <TWEET>"
    exit 1
}

while getopts "lec:u:m:" option
do
    case $option in
        l ) 
            ARG_VIEW=1
            ;;
        e ) 
            ARG_EDIT=1
            ;;
        c ) 
            ARG_CATEGORY=1
            CATEGORY=$OPTARG
            ;;
        u ) 
            ARG_URL=1
            URL=$OPTARG
            ;;
        m ) 
            ARG_TWEET=1
            TWEET=$OPTARG
            ;;
       \? ) 
            usage
            ;;
        * ) 
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

# PROCESS

# Start init
init
check_args

if [ $ARG_VIEW -eq 1 ]; then
    view
fi

if [ $ARG_EDIT -eq 1 ]; then
    edit_conf
fi

if [ ! -z "$CATEGORY" ] || [ ! -z "$URL" ]; then
    tweet
fi

